# Generated by Django 4.2.11 on 2024-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogModels', '0003_author_alter_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
