# Generated by Django 4.2.11 on 2024-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogModels', '0005_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(to='blogModels.category'),
        ),
    ]
