# Generated by Django 4.2.11 on 2024-05-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogModels', '0006_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('AV', 'Aventure'), ('TR', 'Thriller'), ('FS', 'Fantastique'), ('RM', 'Romance'), ('HR', 'Horreur'), ('SF', 'Science-fiction')], max_length=25)),
                ('stock', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogModels.author')),
            ],
        ),
    ]
